# Generated by Django 5.0.7 on 2024-08-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0002_alter_onetimetoken_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onetimetoken',
            table='Flights_onetimetoken',
        ),
    ]
